matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-7
            - libhiredis-dev
            - pkg-config
      env:
        - MATRIX_EVAL="CC=gcc-7"

cache:
    apt: true

before_install:
    - eval "${MATRIX_EVAL}"

language: c
sudo: false
script:
  - make COVERAGE=1
  - cd tests
  - make
  - cd ..
  - bash tests/run.sh

after_success:
  - cd src
  - bash <(curl -s https://codecov.io/bash)
