matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-7
            - libhiredis-dev
            - pkg-config
      env:
        - MATRIX_EVAL="CC=gcc-7"

before_install:
    - eval "${MATRIX_EVAL}"

language: c
sudo: false
script:
  - make COVERAGE=1
  - cd tests
  - make
  - cd ..
  - ./src/zdb --socket /tmp/zdb.sock &
  - sleep 3
  - ./tests/zdbtests
  - pkill zdb
  - sleep 2

after_success:
  - cd src
  - bash <(curl -s https://codecov.io/bash)
