name: Build release
#on:  
#  release:
#    types: [created]
on: [push]
jobs:
  generate:
    name: Create release artifacts
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      - name: Building 0-db
        run: |
          make release
          version=$(grep ZDBD_VERSION zdbd/zdbd.h | awk '{ print $3 }' | sed s/'"'//g)
          cp zdbd/zdb zdb-${version}-linux-amd64-gnu

      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: 'zdb-*-amd64-gnu'

