name: Build release
on:  
  release:
    types: [created]
jobs:
  generate-gnu:
    name: Create release artifacts (gnu)
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git

      - name: Building 0-db
        run: |
          make release
          version=$(grep ZDBD_VERSION zdbd/zdbd.h | awk '{ print $3 }' | sed s/'"'//g)
          cp zdbd/zdb zdb-${version}-linux-amd64-gnu

      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: 'zdb-*-amd64-gnu'

  generate-musl:
    name: Create release artifacts (musl)
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git musl-tools

      - name: Building 0-db
        run: |
          make CC=musl-gcc release
          version=$(grep ZDBD_VERSION zdbd/zdbd.h | awk '{ print $3 }' | sed s/'"'//g)
          cp zdbd/zdb zdb-${version}-linux-amd64-musl

      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: 'zdb-*-amd64-musl'

  static:
    name: Create static release artifact
    runs-on: ubuntu-latest
    container:
      image: alpine:3.13
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master

      - name: Install dependencies
        run: |
          apk add alpine-sdk

      - name: Build production 0-db
        run: |
          cd libzdb
          make release

          cd ../zdbd
          make STATIC=1 release

          version=$(grep ZDBD_VERSION zdbd.h | awk '{ print $3 }' | sed s/'"'//g)
          cp zdb ../zdb-${version}-linux-amd64-static

      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: 'zdb-*-linux-amd64-static'


